INSERT INTO public."Tasks"("Subject", "Description")VALUES('В чем смысл жизни?', 'Задача для первоклассников')
INSERT INTO public."Tasks"("Subject", "Description")VALUES('Можно ли доказать или опровергнуть существования бога?', 'Задача для детсада')
INSERT INTO public."Tasks"("Subject", "Description")VALUES('Будет ли разумное существо радо бессмертию?', 'Задача для подговительных курсах детсада')
INSERT INTO public."Tasks"("Subject", "Description")VALUES('Определение разумного существа', 'Задача для яслей')
INSERT INTO public."Tasks"("Subject", "Description")VALUES('Как преодолеть Великую Тишину', 'Задача для новорожденных')
INSERT INTO public."Tasks"("Subject", "Description")VALUES('Семь смертных грехов мешают счастью человека?', 'Задача для эмбрионов')
INSERT INTO public."Tasks"("Subject", "Description")VALUES('Можно ли постичь абсолютного счастья, не познав горя', 'Задача для эмбрионов')
INSERT INTO public."Tasks"("Subject", "Description")VALUES('Доказательство сущестования паралельных миров или их отсутствие', 'Задача для эмбрионов')
INSERT INTO public."Tasks"("Subject", "Description")VALUES('1+1', 'Задача для эмбрионов')
INSERT INTO public."Tasks"("Subject", "Description")VALUES('Доживет ли человечество до 2200 года от Рождества Xристова', 'Задача для эмбрионов')
INSERT INTO public."Tasks"("Subject", "Description")VALUES('Почему?', 'Задача для эмбрионов')